### ISSUE TITLE
ResourceDictionaries do not support FontFamily and Storyboards

### ISSUE THREAD

**Issue by ala53** [EmptyKeys/UI_Generator#3]
It seems that ResourceDictionary's do not support all the types that the general renderer does.
Perhaps the resources could be inlined into the Xaml / expanded if implementing the Dictionary types is too complex.

**Comment by EmptyKeys** [comment]
Implementing value generator is easy. Inlining XAML and then parsing it on any platform would be super hard. I use XamlReader.Parse in UI Generator. So I prefer to add new types, when there is a need for it  (and it was one of the reasons why UI Generator is open source). :)

I didn't added FontFamily to generator, because I wouldn't be able to auto generate font file for it (you need size etc.). So you would have to add all sprite font files by hand. Would that be a problem? :)

I don't remember, why Storyboard is not supported in resources at this moment. Tho you can use Storyboard in EventTriggers/Styles/ControlTemplates. Maybe I was thinking that reusing just Storyboard does not make sense. I will check that.

**Comment by EmptyKeys** [comment]
Font Family is supported in next version, Storyboard will have to wait a bit.
